### ISSUE TITLE
1.1.4 logical model

### ISSUE THREAD

**Issue by mmorozumi** [cloudsecurityalliance/CSA-Guidance#11]
Logical model is introduced here newly, not in the guidance 3.0.
I understand the concept of the Logical Models, but I do not know which domain refers to this model. Guidance 3.0 uses the NIST model and almost all domains refer to the model.
Could you tell me why the Logical Model is needed in the Guidance?

**Comment by rmogull** [comment]
Sorry for the slow response- notifications didn't work properly so I missed this. The NIST model is still there. The logical model extends on the NIST model since the categorization of the security controls is different in the logical layers. For example, "metastructure" is a key concept to cover the management plane and some other aspects of the behind the scenes cloud infrastructure, and it isn't covered in the NIST model.
